version: '2'

volumes:
    mysql_data:
        driver: local
    mongo_data:
        driver: local
    mysql_config: ./config/mysql
networks:
    brid_network:
        driver: bridge
    
services:
    mysql:
        image: mysql:5.7
        environment:
            LANG: C.UTF-8
            MYSQL_DATABASE: test
            MYSQL_USER: emsoft
            MYSQL_PASSWORD: emsoft
            MYSQL_ROOT_PASSWORD: emsoft
        volumes:
            # Using a custom MySQL configuration file
            - mysql_config:/etc/mysql/conf.d
            # Create a data directory on the host system (outside the container)
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - brid_network

    redis:
        image: redis:3.0
        ports:
            - "6379:6379"
        networks:
            - brid_network
    mongo:
        image: mongo:3.2
        volumes:
            - mongo_data:/data/db
        ports:
            - "27017:27017"
        networks:
            - brid_network
